### ISSUE TITLE
Add post-build event in VS project

### ISSUE THREAD

**Issue by ThirtySomething** [ThirtySomething/Weatherstation#5]
Copy successful build plugins to client/plugins or server/plugins directory by post-build event in VS.

**Comment by ThirtySomething** [comment]
To add the post copy the following lines are required:
```
if not exist "$(SolutionDir)\Client\bin\$(ConfigurationName)\netcoreapp2.0\Plugins\" mkdir "$(SolutionDir)\Client\bin\$(ConfigurationName)\netcoreapp2.0\Plugins\"
copy /Y "$(SolutionDir)\Plugins\DataSink\Console\bin\$(ConfigurationName)\netcoreapp2.0\*.dll" "$(SolutionDir)\Client\bin\$(ConfigurationName)\netcoreapp2.0\Plugins\"
copy /Y "$(SolutionDir)\Plugins\DataSink\Console\bin\$(ConfigurationName)\netcoreapp2.0\*.pdb" "$(SolutionDir)\Client\bin\$(ConfigurationName)\netcoreapp2.0\Plugins\"
```
The first statement is necessary to check and maybe to create the destination directory. The second one is for the plugin (including the external parts like the nuget packages). And the third one is for debugging purposes. All these statements have to be inserted manually - for each plugin. After this is done for the client, duplicate this for the server.

@DonatJR do you know a more generic way to solve this?

**Comment by DonatJR** [comment]
No, I don't think there is a more generic way for solving this. It has to be done once per project.

If the build script is necessary anyway for publishing purposes and additional checks you could also just keep it as ist is and not use the visual studio build events at all...

**Comment by ThirtySomething** [comment]
Okay, so I'll close this issue. Thanks for participating.
